
### Authentication
POST http://consulting-keycloak:8080/realms/im-test/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id = connect-admin-app &
client_secret = secret &
grant_type = client_credentials
