services:
  connect-fake-smtp:
    image: reachfive/fake-smtp-server:latest
    container_name: ${DOCKER_CONTAINER_PREFIX}-connect-fake-smtp
    ports:
      - "1025:1025"
      - "1080:1080"
    networks:
      - net

networks:
  net:
    name: ${DOCKER_NETWORK}
    external: true
