services:
  im-keycloak:
#    image: ${DOCKER_REPOSITORY}connect-admin-keycloak:${CONNECT_ADMIN_KEYCLOAK_VERSION}
    image: ${DOCKER_REPOSITORY}im-keycloak:${VERSION_IM}
    container_name: ${DOCKER_CONTAINER_PREFIX}-im-keycloak
#    network_mode: host
    environment:
      KC_DB_URL: 'jdbc:postgresql://im-keycloak-postgres/im-keycloak'
      KC_DB_PASSWORD: admin
      KC_DB_USERNAME: admin
      KC_DB_SCHEMA: public
      KC_HOSTNAME: ${AUTH_HOST_URL}
      KEYCLOAK_FRONTEND_URL: ${AUTH_HOST_URL}
      KEYCLOAK_ADMIN: ${KC_ROOT_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_ROOT_PASS}
      PROXY_ADDRESS_FORWARDING: "true"
      JDBC_PARAMS: "ssl=false"
      #      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HOSTNAME_STRICT_HTTPS: "true"
    ports:
      - '8080:8080'
    depends_on:
      - im-keycloak-postgres
    networks:
      - net

  im-keycloak-postgres:
    image: postgres
    container_name: ${DOCKER_CONTAINER_PREFIX}-keycloak-postgres
    environment:
      POSTGRES_DB: im-keycloak
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
    networks:
      - net

networks:
  net:
    name: ${DOCKER_NETWORK}
    external: true
