services:
  im-gateway:
    image: ${DOCKER_REPOSITORY}im-gateway:${VERSION_IM}
    container_name: ${DOCKER_CONTAINER_PREFIX}-im
    environment:
      - f2_tenant_issuer-base-uri=${AUTH_HOST_URL}
      - connect_im_keycloak_url=${AUTH_HOST_URL}
      - connect_im_keycloak_realm=master
      - connect_im_keycloak_clientId=${KC_IM_CLIENT_ID}
      - connect_im_keycloak_clientSecret=${KC_IM_CLIENT_SECRET}
    ports:
      - "8009:8009"
    networks:
      - net

networks:
  net:
    name: ${DOCKER_NETWORK}
    external: true
