services:
  im-gateway:
    image: ${DOCKER_REPOSITORY}im-gateway:${VERSION_IM}
    container_name: ${DOCKER_CONTAINER_PREFIX}-im
    environment:
      - i2_issuers[0]_name=local
      - i2_issuers[0]_authUrl=${AUTH_HOST_URL}
      - i2_issuers[0]_realm=im-test
      - i2_issuers[0]_im_clientId=sb-platform-app-im
      - i2_issuers[0]_im_clientSecret=secret
    ports:
      - "8009:8009"
    networks:
      - net

networks:
  net:
    name: ${DOCKER_NETWORK}
    external: true
