services:
  minio:
    image: minio/minio:RELEASE.2022-02-26T02-54-46Z.fips
    container_name: ${DOCKER_CONTAINER_PREFIX}-minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_SERVER_URL=http://${MINIO_HOSTNAME}:9000
      - MINIO_BROWSER=on
    command: server /data --console-address ":9003"
    ports:
      - "9000:9000"
      - "9003:9003"
    volumes:
      - ~/DockerVolumes/minio/trace-consulting/data:/data
    networks:
      - net

  fs-gateway:
    image: ${DOCKER_REPOSITORY}fs-gateway:${VERSION_FS}
    container_name: ${DOCKER_CONTAINER_PREFIX}-fs
    environment:
      - fs_s3_internal-url=http://${MINIO_HOSTNAME}:9000
      - fs_s3_external-url=http://localhost:9000
      - fs_s3_bucket=consulting
      - fs_s3_username=${MINIO_ROOT_USER}
      - fs_s3_password=${MINIO_ROOT_PASSWORD}
      - fs_init_buckets=consulting
      - f2_tenant_issuer-base-uri=
    ports:
      - "8090:8090"
    networks:
      - net

networks:
  net:
    name: ${DOCKER_NETWORK}
    external: true
