name: Dev

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, labeled]
  push:
    branches:
      - main
      - 'release/*'
    tags:
      - '*'


jobs:
  web:
    uses: komune-io/fixers-gradle/.github/workflows/make-jvm-workflow.yml@main
    permissions:
      contents: read
      packages: write
    with:
      make-file: 'make_front.mk'
      on-tag: 'publish promote'
      with-docker-registry-login: 'true'
    secrets:
      PKG_GITHUB_USERNAME: ${{ github.actor }}
      PKG_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKER_PUBLISH_USERNAME: ${{ github.actor }}
      DOCKER_PUBLISH_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      DOCKER_PROMOTE_USERNAME: ${{ secrets.DOCKER_IO_USERNAME }}
      DOCKER_PROMOTE_PASSWORD: ${{ secrets.DOCKER_IO_PASSWORD }}

  keycloak:
    uses: komune-io/fixers-gradle/.github/workflows/make-jvm-workflow.yml@main
    permissions:
      contents: read
      packages: write
    with:
      make-file: 'make_keycloak.mk'
      on-tag: 'publish promote'
      with-docker-registry-login: 'true'
    secrets:
      PKG_GITHUB_USERNAME: ${{ github.actor }}
      PKG_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKER_PUBLISH_USERNAME: ${{ github.actor }}
      DOCKER_PUBLISH_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      DOCKER_PROMOTE_USERNAME: ${{ secrets.DOCKER_IO_USERNAME }}
      DOCKER_PROMOTE_PASSWORD: ${{ secrets.DOCKER_IO_PASSWORD }}
