name: Dev

on:
  pull_request:
    types: [opened, synchronize, labeled]
  push:
    branches:
      - main
      - 'release/*'

jobs:
  docker:
    uses: komune-io/fixers-gradle/.github/workflows/make-jvm-workflow.yml@main
    permissions:
      contents: read
      packages: write
    with:
      make-file: 'docker.mk'
      with-docker-registry-login: 'true'
      docker-buildx-platform: linux/amd64,linux/arm64
    secrets:
      PKG_GITHUB_USERNAME: ${{ github.actor }}
      PKG_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKER_PUBLISH_USERNAME: ${{ github.actor }}
      DOCKER_PUBLISH_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      DOCKER_PROMOTE_USERNAME: ${{ secrets.DOCKER_IO_USERNAME }}
      DOCKER_PROMOTE_PASSWORD: ${{ secrets.DOCKER_IO_PASSWORD }}
