name: Dev

on:
  pull_request:
    types: [opened, synchronize, labeled]
  push:
    branches:
      - main
      - 'release/*'

jobs:
  docker:
    uses: komune-io/fixers-gradle/.github/workflows/make-nodejs-workflow.yml@79edc9c3671cac13add451b69e994976a192b657
    permissions:
      contents: read
      packages: write
    with:
      base-dir: platform/web
      with-docker-registry-login: 'true'
    secrets:
      NPM_PKG_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKER_PUBLISH_USERNAME: ${{ github.actor }}
      DOCKER_PUBLISH_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      DOCKER_PROMOTE_USERNAME: ${{ secrets.DOCKER_IO_USERNAME }}
      DOCKER_PROMOTE_PASSWORD: ${{ secrets.DOCKER_IO_PASSWORD }}
